// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgXXOCGpT0eobsysEiawMTny0QOI4Gcr0',
    appId: '1:870098037601:android:cdeb73d403d9131decf320',
    messagingSenderId: '870098037601',
    projectId: 'heaven-living',
    storageBucket: 'heaven-living.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gmcMwHtgZJIS_L7AEsI9_g7OzxT_aYY',
    appId: '1:870098037601:ios:a683df1bf26ad032ecf320',
    messagingSenderId: '870098037601',
    projectId: 'heaven-living',
    storageBucket: 'heaven-living.appspot.com',
    iosBundleId: 'com.weronz.heavensliving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-gmcMwHtgZJIS_L7AEsI9_g7OzxT_aYY',
    appId: '1:870098037601:ios:0ad482d15fe575beecf320',
    messagingSenderId: '870098037601',
    projectId: 'heaven-living',
    storageBucket: 'heaven-living.appspot.com',
    iosBundleId: 'com.example.heavensStudents',

    
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL52StHxrivv3w1QMu9Gqp8bb2CFqFT-U',
    appId: '1:870098037601:web:baa2be115b1d5a82ecf320',
    messagingSenderId: '870098037601',
    projectId: 'heaven-living',
    authDomain: 'heaven-living.firebaseapp.com',
    storageBucket: 'heaven-living.appspot.com',
    measurementId: 'G-GVFDY84K4Y',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL52StHxrivv3w1QMu9Gqp8bb2CFqFT-U',
    appId: '1:870098037601:web:cab49a951f7afb97ecf320',
    messagingSenderId: '870098037601',
    projectId: 'heaven-living',
    authDomain: 'heaven-living.firebaseapp.com',
    storageBucket: 'heaven-living.appspot.com',
    measurementId: 'G-X5FR90F1WR',
  );

}